language: 
    python

sudo:
    - "true"

python:
    - "3.5"

install:
    - ls
    - pip install -r requirements.txt
    - pip install coverage 

script:
    - coverage run --source=. -m unittest tests/*.py        
    - coverage report -m
    - ls
